apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: gcr.io/xs-amiable-bonus-6/django-image:1.8
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "secret-password"
        - name: DJANGO_SETTINGS_MODULE
          value: "project.settings.prod"
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        - name: RABBITMQ_DEFAULT_VHOST
          value: "/"
        - name: SECRET_KEY
          value: "_i%mh%l&)sd*cqfrx0emua)o84+*!+5w29m%c03kqb4eym+6gc"
        ports:
        - containerPort: 8000
