version: '2'
services:
    django:
        extends:
            file: common.yml
            service: django
        env_file:
            - django/django-variables.env
            - postgres/postgres-variables.env
            - rabbitmq/rabbitmq-variables.env
        volumes:
            - static:/srv/django/static
        links:
            - postgres:postgres.default.svc.cluster.local
            - rabbitmq:rabbitmq.default.svc.cluster.local
            - redis:redis

    celery:
        image: django-image
        env_file:
            - django/django-variables.env
            - postgres/postgres-variables.env
            - rabbitmq/rabbitmq-variables.env
        links:
            - postgres:postgres.default.svc.cluster.local
            - rabbitmq:rabbitmq.default.svc.cluster.local
            - redis:redis
        command: celery -A project worker -l warning

    nginx:
        build: ./nginx
        links:
            - django:django
        volumes_from:
            - django

    react:
        build: ./react

    postgres:
        image: postgres
        env_file:
            - postgres/postgres-variables.env

    redis:
        image: redis:3.2

    rabbitmq:
        image: rabbitmq:3.6
        env_file:
            - rabbitmq/rabbitmq-variables.env

volumes:
    static: {}
